### ISSUE TITLE
Capturing og:image with Puppeteer throws errors

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#74]
Just checked the log and there are a lot of failed serverless functions since May 25, the day #66 was merged.

![38FD0AA4-4E1D-48A3-ACF4-7C1847886CD5](https://user-images.githubusercontent.com/44609036/171451909-d53cdbc2-4b93-4e3d-bcf7-f95b256dd0bd.jpeg)

The error log as reported is

```
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).
    at ChromeLauncher.launch (/var/task/packages/client/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:105:23)
    at async internalCaptureWebsite (file:///var/task/packages/client/node_modules/capture-website/index.js:148:33)
    at async getOgImage (/var/task/packages/client/.next/server/chunks/347.js:74:20)
    at async getStaticProps (/var/task/packages/client/.next/server/pages/orbital/log-joulev.js:305:19)
    at async Object.renderToHTML (/var/task/packages/client/node_modules/next/dist/server/render.js:492:20)
    at async doRender (/var/task/packages/client/node_modules/next/dist/server/base-server.js:901:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/var/task/packages/client/node_modules/next/dist/server/base-server.js:1006:28)
    at async /var/task/packages/client/node_modules/next/dist/server/response-cache.js:74:36 {
  page: '/orbital/log-joulev'
}
```

Now this is gonna be a headache to deal with browsers and Puppeteer on AWS.

Quite strange that despite the error the image can still be captured successfully.

**Comment by joulev** [comment]
So the captures were successful after all. Vercel log for fb9bbc48abd5670f7c3e562a571193c2556efc73:

```
[13:42:14.093] info  - Checking validity of types...
[13:42:26.383] info  - Creating an optimized production build...
[13:43:06.284] info  - Compiled successfully
[13:43:06.284] info  - Collecting page data...
[13:43:09.545] info  - Generating static pages (0/15)
[13:43:09.594] info  - Generating static pages (3/15)
[13:43:11.823] Capturing image for "Project Log for Nguyen Viet Anh" successfully
[13:43:11.868] info  - Generating static pages (7/15)
[13:43:11.881] Capturing image for "Project Log for Vu Van Dung" successfully
[13:43:11.891] Capturing image for "ezkomment @ NUS Orbital" successfully
[13:43:13.519] Capturing image for "Orbital 2022 Milestone 1 README" successfully
[13:43:13.634] Capturing image for "Orbital 2022 Proposal" successfully
[13:43:13.648] info  - Generating static pages (11/15)
[13:43:14.133] Capturing image for "undefined" successfully
[13:43:15.571] Capturing image for "Getting started" successfully
[13:43:16.141] Capturing image for "Basic features: Pages" successfully
[13:43:17.123] info  - Generating static pages (15/15)
[13:43:17.142] info  - Finalizing page optimization...
```

On closer log inspection from both recorded error logs, it appears that normal `getStaticProps` can run this well, but `getStaticProps` with ISR fails (since only `/orbital/log-joulev` has the issue). Strange that the ISR is for 86400 seconds (one day), the function should not have been executed that many times.

**Comment by joulev** [comment]
<img width="505" alt="image" src="https://user-images.githubusercontent.com/44609036/172033737-e3d55607-a647-4186-ab7e-ca7de55817d4.png">

Looking good. This is how it should be.
